code_bank:
  identifier: 
  chunk_size_in_tokens: 512
  overlap_size_in_tokens: 64
  embedding_model: "all-MiniLM-L6-v2"



rag_agent:
- indexing:
- retrieval:
    lookup_chunks: 12
- generation:
    temperature: 0.8
    top_p: 0.95
    